/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SidebarLayoutRouteImport } from './routes/_sidebar-layout'
import { Route as SidebarLayoutSettingsRouteImport } from './routes/_sidebar-layout.settings'
import { Route as SidebarLayoutChatLayoutRouteImport } from './routes/_sidebar-layout._chat-layout'
import { Route as SidebarLayoutStoriesIndexRouteImport } from './routes/_sidebar-layout.stories.index'
import { Route as SidebarLayoutSettingsIndexRouteImport } from './routes/_sidebar-layout.settings.index'
import { Route as SidebarLayoutChatLayoutIndexRouteImport } from './routes/_sidebar-layout._chat-layout.index'
import { Route as SidebarLayoutSettingsUsageRouteImport } from './routes/_sidebar-layout.settings.usage'
import { Route as SidebarLayoutSettingsProjectRouteImport } from './routes/_sidebar-layout.settings.project'
import { Route as SidebarLayoutSettingsMemoryRouteImport } from './routes/_sidebar-layout.settings.memory'
import { Route as SidebarLayoutSettingsGeneralRouteImport } from './routes/_sidebar-layout.settings.general'
import { Route as SidebarLayoutChatLayoutChatIdRouteImport } from './routes/_sidebar-layout._chat-layout.$chatId'
import { Route as SidebarLayoutSettingsProjectIndexRouteImport } from './routes/_sidebar-layout.settings.project.index'
import { Route as SidebarLayoutStoriesSharedShareIdRouteImport } from './routes/_sidebar-layout.stories.shared.$shareId'
import { Route as SidebarLayoutSettingsProjectTeamsRouteImport } from './routes/_sidebar-layout.settings.project.teams'
import { Route as SidebarLayoutSettingsProjectTeamRouteImport } from './routes/_sidebar-layout.settings.project.team'
import { Route as SidebarLayoutSettingsProjectSlackRouteImport } from './routes/_sidebar-layout.settings.project.slack'
import { Route as SidebarLayoutSettingsProjectModelsRouteImport } from './routes/_sidebar-layout.settings.project.models'
import { Route as SidebarLayoutSettingsProjectMcpServersRouteImport } from './routes/_sidebar-layout.settings.project.mcp-servers'
import { Route as SidebarLayoutSettingsProjectAgentRouteImport } from './routes/_sidebar-layout.settings.project.agent'
import { Route as SidebarLayoutStoriesPreviewChatIdStoryIdRouteImport } from './routes/_sidebar-layout.stories.preview.$chatId.$storyId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarLayoutRoute = SidebarLayoutRouteImport.update({
  id: '/_sidebar-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarLayoutSettingsRoute = SidebarLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SidebarLayoutRoute,
} as any)
const SidebarLayoutChatLayoutRoute = SidebarLayoutChatLayoutRouteImport.update({
  id: '/_chat-layout',
  getParentRoute: () => SidebarLayoutRoute,
} as any)
const SidebarLayoutStoriesIndexRoute =
  SidebarLayoutStoriesIndexRouteImport.update({
    id: '/stories/',
    path: '/stories/',
    getParentRoute: () => SidebarLayoutRoute,
  } as any)
const SidebarLayoutSettingsIndexRoute =
  SidebarLayoutSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutChatLayoutIndexRoute =
  SidebarLayoutChatLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SidebarLayoutChatLayoutRoute,
  } as any)
const SidebarLayoutSettingsUsageRoute =
  SidebarLayoutSettingsUsageRouteImport.update({
    id: '/usage',
    path: '/usage',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsProjectRoute =
  SidebarLayoutSettingsProjectRouteImport.update({
    id: '/project',
    path: '/project',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsMemoryRoute =
  SidebarLayoutSettingsMemoryRouteImport.update({
    id: '/memory',
    path: '/memory',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutSettingsGeneralRoute =
  SidebarLayoutSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => SidebarLayoutSettingsRoute,
  } as any)
const SidebarLayoutChatLayoutChatIdRoute =
  SidebarLayoutChatLayoutChatIdRouteImport.update({
    id: '/$chatId',
    path: '/$chatId',
    getParentRoute: () => SidebarLayoutChatLayoutRoute,
  } as any)
const SidebarLayoutSettingsProjectIndexRoute =
  SidebarLayoutSettingsProjectIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutStoriesSharedShareIdRoute =
  SidebarLayoutStoriesSharedShareIdRouteImport.update({
    id: '/stories/shared/$shareId',
    path: '/stories/shared/$shareId',
    getParentRoute: () => SidebarLayoutRoute,
  } as any)
const SidebarLayoutSettingsProjectTeamsRoute =
  SidebarLayoutSettingsProjectTeamsRouteImport.update({
    id: '/teams',
    path: '/teams',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectTeamRoute =
  SidebarLayoutSettingsProjectTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectSlackRoute =
  SidebarLayoutSettingsProjectSlackRouteImport.update({
    id: '/slack',
    path: '/slack',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectModelsRoute =
  SidebarLayoutSettingsProjectModelsRouteImport.update({
    id: '/models',
    path: '/models',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectMcpServersRoute =
  SidebarLayoutSettingsProjectMcpServersRouteImport.update({
    id: '/mcp-servers',
    path: '/mcp-servers',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutSettingsProjectAgentRoute =
  SidebarLayoutSettingsProjectAgentRouteImport.update({
    id: '/agent',
    path: '/agent',
    getParentRoute: () => SidebarLayoutSettingsProjectRoute,
  } as any)
const SidebarLayoutStoriesPreviewChatIdStoryIdRoute =
  SidebarLayoutStoriesPreviewChatIdStoryIdRouteImport.update({
    id: '/stories/preview/$chatId/$storyId',
    path: '/stories/preview/$chatId/$storyId',
    getParentRoute: () => SidebarLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof SidebarLayoutChatLayoutIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/settings': typeof SidebarLayoutSettingsRouteWithChildren
  '/$chatId': typeof SidebarLayoutChatLayoutChatIdRoute
  '/settings/general': typeof SidebarLayoutSettingsGeneralRoute
  '/settings/memory': typeof SidebarLayoutSettingsMemoryRoute
  '/settings/project': typeof SidebarLayoutSettingsProjectRouteWithChildren
  '/settings/usage': typeof SidebarLayoutSettingsUsageRoute
  '/settings/': typeof SidebarLayoutSettingsIndexRoute
  '/stories/': typeof SidebarLayoutStoriesIndexRoute
  '/settings/project/agent': typeof SidebarLayoutSettingsProjectAgentRoute
  '/settings/project/mcp-servers': typeof SidebarLayoutSettingsProjectMcpServersRoute
  '/settings/project/models': typeof SidebarLayoutSettingsProjectModelsRoute
  '/settings/project/slack': typeof SidebarLayoutSettingsProjectSlackRoute
  '/settings/project/team': typeof SidebarLayoutSettingsProjectTeamRoute
  '/settings/project/teams': typeof SidebarLayoutSettingsProjectTeamsRoute
  '/stories/shared/$shareId': typeof SidebarLayoutStoriesSharedShareIdRoute
  '/settings/project/': typeof SidebarLayoutSettingsProjectIndexRoute
  '/stories/preview/$chatId/$storyId': typeof SidebarLayoutStoriesPreviewChatIdStoryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof SidebarLayoutChatLayoutIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$chatId': typeof SidebarLayoutChatLayoutChatIdRoute
  '/settings/general': typeof SidebarLayoutSettingsGeneralRoute
  '/settings/memory': typeof SidebarLayoutSettingsMemoryRoute
  '/settings/usage': typeof SidebarLayoutSettingsUsageRoute
  '/settings': typeof SidebarLayoutSettingsIndexRoute
  '/stories': typeof SidebarLayoutStoriesIndexRoute
  '/settings/project/agent': typeof SidebarLayoutSettingsProjectAgentRoute
  '/settings/project/mcp-servers': typeof SidebarLayoutSettingsProjectMcpServersRoute
  '/settings/project/models': typeof SidebarLayoutSettingsProjectModelsRoute
  '/settings/project/slack': typeof SidebarLayoutSettingsProjectSlackRoute
  '/settings/project/team': typeof SidebarLayoutSettingsProjectTeamRoute
  '/settings/project/teams': typeof SidebarLayoutSettingsProjectTeamsRoute
  '/stories/shared/$shareId': typeof SidebarLayoutStoriesSharedShareIdRoute
  '/settings/project': typeof SidebarLayoutSettingsProjectIndexRoute
  '/stories/preview/$chatId/$storyId': typeof SidebarLayoutStoriesPreviewChatIdStoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_sidebar-layout': typeof SidebarLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_sidebar-layout/_chat-layout': typeof SidebarLayoutChatLayoutRouteWithChildren
  '/_sidebar-layout/settings': typeof SidebarLayoutSettingsRouteWithChildren
  '/_sidebar-layout/_chat-layout/$chatId': typeof SidebarLayoutChatLayoutChatIdRoute
  '/_sidebar-layout/settings/general': typeof SidebarLayoutSettingsGeneralRoute
  '/_sidebar-layout/settings/memory': typeof SidebarLayoutSettingsMemoryRoute
  '/_sidebar-layout/settings/project': typeof SidebarLayoutSettingsProjectRouteWithChildren
  '/_sidebar-layout/settings/usage': typeof SidebarLayoutSettingsUsageRoute
  '/_sidebar-layout/_chat-layout/': typeof SidebarLayoutChatLayoutIndexRoute
  '/_sidebar-layout/settings/': typeof SidebarLayoutSettingsIndexRoute
  '/_sidebar-layout/stories/': typeof SidebarLayoutStoriesIndexRoute
  '/_sidebar-layout/settings/project/agent': typeof SidebarLayoutSettingsProjectAgentRoute
  '/_sidebar-layout/settings/project/mcp-servers': typeof SidebarLayoutSettingsProjectMcpServersRoute
  '/_sidebar-layout/settings/project/models': typeof SidebarLayoutSettingsProjectModelsRoute
  '/_sidebar-layout/settings/project/slack': typeof SidebarLayoutSettingsProjectSlackRoute
  '/_sidebar-layout/settings/project/team': typeof SidebarLayoutSettingsProjectTeamRoute
  '/_sidebar-layout/settings/project/teams': typeof SidebarLayoutSettingsProjectTeamsRoute
  '/_sidebar-layout/stories/shared/$shareId': typeof SidebarLayoutStoriesSharedShareIdRoute
  '/_sidebar-layout/settings/project/': typeof SidebarLayoutSettingsProjectIndexRoute
  '/_sidebar-layout/stories/preview/$chatId/$storyId': typeof SidebarLayoutStoriesPreviewChatIdStoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/settings'
    | '/$chatId'
    | '/settings/general'
    | '/settings/memory'
    | '/settings/project'
    | '/settings/usage'
    | '/settings/'
    | '/stories/'
    | '/settings/project/agent'
    | '/settings/project/mcp-servers'
    | '/settings/project/models'
    | '/settings/project/slack'
    | '/settings/project/team'
    | '/settings/project/teams'
    | '/stories/shared/$shareId'
    | '/settings/project/'
    | '/stories/preview/$chatId/$storyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/$chatId'
    | '/settings/general'
    | '/settings/memory'
    | '/settings/usage'
    | '/settings'
    | '/stories'
    | '/settings/project/agent'
    | '/settings/project/mcp-servers'
    | '/settings/project/models'
    | '/settings/project/slack'
    | '/settings/project/team'
    | '/settings/project/teams'
    | '/stories/shared/$shareId'
    | '/settings/project'
    | '/stories/preview/$chatId/$storyId'
  id:
    | '__root__'
    | '/_sidebar-layout'
    | '/login'
    | '/signup'
    | '/_sidebar-layout/_chat-layout'
    | '/_sidebar-layout/settings'
    | '/_sidebar-layout/_chat-layout/$chatId'
    | '/_sidebar-layout/settings/general'
    | '/_sidebar-layout/settings/memory'
    | '/_sidebar-layout/settings/project'
    | '/_sidebar-layout/settings/usage'
    | '/_sidebar-layout/_chat-layout/'
    | '/_sidebar-layout/settings/'
    | '/_sidebar-layout/stories/'
    | '/_sidebar-layout/settings/project/agent'
    | '/_sidebar-layout/settings/project/mcp-servers'
    | '/_sidebar-layout/settings/project/models'
    | '/_sidebar-layout/settings/project/slack'
    | '/_sidebar-layout/settings/project/team'
    | '/_sidebar-layout/settings/project/teams'
    | '/_sidebar-layout/stories/shared/$shareId'
    | '/_sidebar-layout/settings/project/'
    | '/_sidebar-layout/stories/preview/$chatId/$storyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SidebarLayoutRoute: typeof SidebarLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar-layout': {
      id: '/_sidebar-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar-layout/settings': {
      id: '/_sidebar-layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SidebarLayoutSettingsRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/_chat-layout': {
      id: '/_sidebar-layout/_chat-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarLayoutChatLayoutRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/stories/': {
      id: '/_sidebar-layout/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof SidebarLayoutStoriesIndexRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/settings/': {
      id: '/_sidebar-layout/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SidebarLayoutSettingsIndexRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/_chat-layout/': {
      id: '/_sidebar-layout/_chat-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SidebarLayoutChatLayoutIndexRouteImport
      parentRoute: typeof SidebarLayoutChatLayoutRoute
    }
    '/_sidebar-layout/settings/usage': {
      id: '/_sidebar-layout/settings/usage'
      path: '/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof SidebarLayoutSettingsUsageRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/project': {
      id: '/_sidebar-layout/settings/project'
      path: '/project'
      fullPath: '/settings/project'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/memory': {
      id: '/_sidebar-layout/settings/memory'
      path: '/memory'
      fullPath: '/settings/memory'
      preLoaderRoute: typeof SidebarLayoutSettingsMemoryRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/settings/general': {
      id: '/_sidebar-layout/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof SidebarLayoutSettingsGeneralRouteImport
      parentRoute: typeof SidebarLayoutSettingsRoute
    }
    '/_sidebar-layout/_chat-layout/$chatId': {
      id: '/_sidebar-layout/_chat-layout/$chatId'
      path: '/$chatId'
      fullPath: '/$chatId'
      preLoaderRoute: typeof SidebarLayoutChatLayoutChatIdRouteImport
      parentRoute: typeof SidebarLayoutChatLayoutRoute
    }
    '/_sidebar-layout/settings/project/': {
      id: '/_sidebar-layout/settings/project/'
      path: '/'
      fullPath: '/settings/project/'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectIndexRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/stories/shared/$shareId': {
      id: '/_sidebar-layout/stories/shared/$shareId'
      path: '/stories/shared/$shareId'
      fullPath: '/stories/shared/$shareId'
      preLoaderRoute: typeof SidebarLayoutStoriesSharedShareIdRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
    '/_sidebar-layout/settings/project/teams': {
      id: '/_sidebar-layout/settings/project/teams'
      path: '/teams'
      fullPath: '/settings/project/teams'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectTeamsRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/team': {
      id: '/_sidebar-layout/settings/project/team'
      path: '/team'
      fullPath: '/settings/project/team'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectTeamRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/slack': {
      id: '/_sidebar-layout/settings/project/slack'
      path: '/slack'
      fullPath: '/settings/project/slack'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectSlackRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/models': {
      id: '/_sidebar-layout/settings/project/models'
      path: '/models'
      fullPath: '/settings/project/models'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectModelsRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/mcp-servers': {
      id: '/_sidebar-layout/settings/project/mcp-servers'
      path: '/mcp-servers'
      fullPath: '/settings/project/mcp-servers'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectMcpServersRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/settings/project/agent': {
      id: '/_sidebar-layout/settings/project/agent'
      path: '/agent'
      fullPath: '/settings/project/agent'
      preLoaderRoute: typeof SidebarLayoutSettingsProjectAgentRouteImport
      parentRoute: typeof SidebarLayoutSettingsProjectRoute
    }
    '/_sidebar-layout/stories/preview/$chatId/$storyId': {
      id: '/_sidebar-layout/stories/preview/$chatId/$storyId'
      path: '/stories/preview/$chatId/$storyId'
      fullPath: '/stories/preview/$chatId/$storyId'
      preLoaderRoute: typeof SidebarLayoutStoriesPreviewChatIdStoryIdRouteImport
      parentRoute: typeof SidebarLayoutRoute
    }
  }
}

interface SidebarLayoutChatLayoutRouteChildren {
  SidebarLayoutChatLayoutChatIdRoute: typeof SidebarLayoutChatLayoutChatIdRoute
  SidebarLayoutChatLayoutIndexRoute: typeof SidebarLayoutChatLayoutIndexRoute
}

const SidebarLayoutChatLayoutRouteChildren: SidebarLayoutChatLayoutRouteChildren =
  {
    SidebarLayoutChatLayoutChatIdRoute: SidebarLayoutChatLayoutChatIdRoute,
    SidebarLayoutChatLayoutIndexRoute: SidebarLayoutChatLayoutIndexRoute,
  }

const SidebarLayoutChatLayoutRouteWithChildren =
  SidebarLayoutChatLayoutRoute._addFileChildren(
    SidebarLayoutChatLayoutRouteChildren,
  )

interface SidebarLayoutSettingsProjectRouteChildren {
  SidebarLayoutSettingsProjectAgentRoute: typeof SidebarLayoutSettingsProjectAgentRoute
  SidebarLayoutSettingsProjectMcpServersRoute: typeof SidebarLayoutSettingsProjectMcpServersRoute
  SidebarLayoutSettingsProjectModelsRoute: typeof SidebarLayoutSettingsProjectModelsRoute
  SidebarLayoutSettingsProjectSlackRoute: typeof SidebarLayoutSettingsProjectSlackRoute
  SidebarLayoutSettingsProjectTeamRoute: typeof SidebarLayoutSettingsProjectTeamRoute
  SidebarLayoutSettingsProjectTeamsRoute: typeof SidebarLayoutSettingsProjectTeamsRoute
  SidebarLayoutSettingsProjectIndexRoute: typeof SidebarLayoutSettingsProjectIndexRoute
}

const SidebarLayoutSettingsProjectRouteChildren: SidebarLayoutSettingsProjectRouteChildren =
  {
    SidebarLayoutSettingsProjectAgentRoute:
      SidebarLayoutSettingsProjectAgentRoute,
    SidebarLayoutSettingsProjectMcpServersRoute:
      SidebarLayoutSettingsProjectMcpServersRoute,
    SidebarLayoutSettingsProjectModelsRoute:
      SidebarLayoutSettingsProjectModelsRoute,
    SidebarLayoutSettingsProjectSlackRoute:
      SidebarLayoutSettingsProjectSlackRoute,
    SidebarLayoutSettingsProjectTeamRoute:
      SidebarLayoutSettingsProjectTeamRoute,
    SidebarLayoutSettingsProjectTeamsRoute:
      SidebarLayoutSettingsProjectTeamsRoute,
    SidebarLayoutSettingsProjectIndexRoute:
      SidebarLayoutSettingsProjectIndexRoute,
  }

const SidebarLayoutSettingsProjectRouteWithChildren =
  SidebarLayoutSettingsProjectRoute._addFileChildren(
    SidebarLayoutSettingsProjectRouteChildren,
  )

interface SidebarLayoutSettingsRouteChildren {
  SidebarLayoutSettingsGeneralRoute: typeof SidebarLayoutSettingsGeneralRoute
  SidebarLayoutSettingsMemoryRoute: typeof SidebarLayoutSettingsMemoryRoute
  SidebarLayoutSettingsProjectRoute: typeof SidebarLayoutSettingsProjectRouteWithChildren
  SidebarLayoutSettingsUsageRoute: typeof SidebarLayoutSettingsUsageRoute
  SidebarLayoutSettingsIndexRoute: typeof SidebarLayoutSettingsIndexRoute
}

const SidebarLayoutSettingsRouteChildren: SidebarLayoutSettingsRouteChildren = {
  SidebarLayoutSettingsGeneralRoute: SidebarLayoutSettingsGeneralRoute,
  SidebarLayoutSettingsMemoryRoute: SidebarLayoutSettingsMemoryRoute,
  SidebarLayoutSettingsProjectRoute:
    SidebarLayoutSettingsProjectRouteWithChildren,
  SidebarLayoutSettingsUsageRoute: SidebarLayoutSettingsUsageRoute,
  SidebarLayoutSettingsIndexRoute: SidebarLayoutSettingsIndexRoute,
}

const SidebarLayoutSettingsRouteWithChildren =
  SidebarLayoutSettingsRoute._addFileChildren(
    SidebarLayoutSettingsRouteChildren,
  )

interface SidebarLayoutRouteChildren {
  SidebarLayoutChatLayoutRoute: typeof SidebarLayoutChatLayoutRouteWithChildren
  SidebarLayoutSettingsRoute: typeof SidebarLayoutSettingsRouteWithChildren
  SidebarLayoutStoriesIndexRoute: typeof SidebarLayoutStoriesIndexRoute
  SidebarLayoutStoriesSharedShareIdRoute: typeof SidebarLayoutStoriesSharedShareIdRoute
  SidebarLayoutStoriesPreviewChatIdStoryIdRoute: typeof SidebarLayoutStoriesPreviewChatIdStoryIdRoute
}

const SidebarLayoutRouteChildren: SidebarLayoutRouteChildren = {
  SidebarLayoutChatLayoutRoute: SidebarLayoutChatLayoutRouteWithChildren,
  SidebarLayoutSettingsRoute: SidebarLayoutSettingsRouteWithChildren,
  SidebarLayoutStoriesIndexRoute: SidebarLayoutStoriesIndexRoute,
  SidebarLayoutStoriesSharedShareIdRoute:
    SidebarLayoutStoriesSharedShareIdRoute,
  SidebarLayoutStoriesPreviewChatIdStoryIdRoute:
    SidebarLayoutStoriesPreviewChatIdStoryIdRoute,
}

const SidebarLayoutRouteWithChildren = SidebarLayoutRoute._addFileChildren(
  SidebarLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SidebarLayoutRoute: SidebarLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
